# Generated by Django 4.1.3 on 2022-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0003_alter_userdetails_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheduleofcharges',
            name='user_type',
            field=models.CharField(choices=[('', 'select'), (1, 'premium'), (2, 'Non Premium')], max_length=50),
        ),
    ]
